<?php

namespace Database\Seeders;

use App\Models\Classroom;
use App\Models\ClassroomActivity;
use App\Models\GalleryAlbum;
use Illuminate\Database\Seeder;

/**
 * The photo library the nursery sent us. The image files live in public/media (committed with the
 * code), this seeder recreates the database rows that place each photo on the right class, activity
 * or album. Generated from the local site with scratch/gen_photo_seeder.php after an import; to add
 * new photos, run `php artisan photos:import "<folder>"` locally and regenerate.
 *
 * Owners that already have photos are left alone, so the seeder is safe to re-run.
 */
class PhotoSeeder extends Seeder
{
    /** [owner type, class or album slug, activity slug, path, alt, width, height, sort] */
    private const PHOTOS = [
        [  'class_activity',  'candy',  'arabic',  'uploads/classroom_activity/22/Mqw7fpc5eyMYZop1WTmxK8G0.jpg',  'Arabic class in the Candy class at Marshmallow Nursery',  771,  1024,  0],
        [  'class_activity',  'candy',  'arabic',  'uploads/classroom_activity/22/JC1b3iSVAvP9cwz1mRxkdJVp.jpeg',  'Arabic class in the Candy class at Marshmallow Nursery',  768,  1024,  1],
        [  'class_activity',  'candy',  'topic-booklet',  'uploads/classroom_activity/20/ePdkIaGlawDkkvoXnA4f2umN.jpeg',  'Monthly topic booklet in the Candy class at Marshmallow Nursery',  1180,  1078,  0],
        [  'class_activity',  'candy',  'art-craft',  'uploads/classroom_activity/25/CkzfHLOw82skb8A3TiORKyv4.jpeg',  'Art & crafts in the Candy class at Marshmallow Nursery',  960,  1280,  0],
        [  'class_activity',  'candy',  'english-academic',  'uploads/classroom_activity/19/SRCgcZVf1NS89d5yT77fyZtM.jpg',  'English academic class in the Candy class at Marshmallow Nursery',  768,  1024,  0],
        [  'class_activity',  'candy',  'events',  'uploads/classroom_activity/29/7avACAZHJ0yPPhOLHKKTNNE0.jpg',  'Events & celebrations in the Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'candy',  'events',  'uploads/classroom_activity/29/V7a9m8qU2xHABVlA6OOhMjmR.jpg',  'Events & celebrations in the Candy class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'candy',  'events',  'uploads/classroom_activity/29/QbGut0qwLoTdhZ4mwL4bhI3Q.jpg',  'Events & celebrations in the Candy class at Marshmallow Nursery',  640,  640,  2],
        [  'class_activity',  'candy',  'events',  'uploads/classroom_activity/29/4B4hUp411ANiY8kUOL2ebreK.jpg',  'Events & celebrations in the Candy class at Marshmallow Nursery',  640,  640,  3],
        [  'class_activity',  'candy',  'events',  'uploads/classroom_activity/29/1z2RZZz6Y3NH1zOiAYZZ33hk.jpg',  'Events & celebrations in the Candy class at Marshmallow Nursery',  640,  640,  4],
        [  'class_activity',  'candy',  'feelings',  'uploads/classroom_activity/26/gpCGs6VMKFaHfAS3wrCPQuAU.jpeg',  'Feelings & manners in the Candy class at Marshmallow Nursery',  727,  1024,  0],
        [  'class_activity',  'candy',  'feelings',  'uploads/classroom_activity/26/BCH751nQTZ950QCsYPxf5Fuz.jpeg',  'Feelings & manners in the Candy class at Marshmallow Nursery',  768,  1024,  1],
        [  'class_activity',  'candy',  'feelings',  'uploads/classroom_activity/26/xr5k7kR2InbcpycA8lA3958R.jpeg',  'Feelings & manners in the Candy class at Marshmallow Nursery',  768,  1024,  2],
        [  'class_activity',  'candy',  'motor-skills',  'uploads/classroom_activity/67/5J9w4wxuyNdDeoixVCzqO4Jn.jpg',  'Fine & gross motor skills in the Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'candy',  'motor-skills',  'uploads/classroom_activity/67/J9uPmdqoYScklcq6rmPAuSJQ.jpeg',  'Fine & gross motor skills in the Candy class at Marshmallow Nursery',  1280,  960,  1],
        [  'class_activity',  'candy',  'french',  'uploads/classroom_activity/21/EF7RBAp6F0bj79ZRcLnoBicv.jpg',  'French class in the Candy class at Marshmallow Nursery',  1024,  768,  0],
        [  'class_activity',  'candy',  'garden-time',  'uploads/classroom_activity/68/1r1m8M8ySdf8tZxq6dVicTeh.jpg',  'Garden time in the Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'candy',  'garden-time',  'uploads/classroom_activity/68/jO5m8dRQdaCmFoceQWbdhEbk.jpeg',  'Garden time in the Candy class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'candy',  'motor-skills',  'uploads/classroom_activity/67/WZg3Mvh4aAEaN9y9VoopqvOy.jpg',  'Fine & gross motor skills in the Candy class at Marshmallow Nursery',  640,  640,  2],
        [  'class_activity',  'candy',  'motor-skills',  'uploads/classroom_activity/67/aNi1dcC3YziBDPCU1E0MBXT2.jpeg',  'Fine & gross motor skills in the Candy class at Marshmallow Nursery',  960,  1280,  3],
        [  'class_activity',  'candy',  'gymnastics',  'uploads/classroom_activity/23/92e1ZkacR3QnymLFLXF0GTU8.jpg',  'Gymnastics in the Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'candy',  'gymnastics',  'uploads/classroom_activity/23/lTzrUbt1Xw3nCsOrajUog2es.jpg',  'Gymnastics in the Candy class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'candy',  'science-experiments',  'uploads/classroom_activity/24/BJpAYx0l9e4GUsgQJpGDJM6q.jpg',  'Science experiments in the Candy class at Marshmallow Nursery',  768,  1024,  0],
        [  'class_activity',  'candy',  'science-experiments',  'uploads/classroom_activity/24/L3ZEvqaqIvWvRBSUanh6Nrp5.jpg',  'Science experiments in the Candy class at Marshmallow Nursery',  1024,  768,  1],
        [  'class_activity',  'candy',  'storytelling',  'uploads/classroom_activity/28/BKNhE4dH5IRBe4CzArHJqIWe.jpeg',  'Storytelling in the Candy class at Marshmallow Nursery',  1024,  768,  0],
        [  'class_activity',  'cotton-candy',  'arabic',  'uploads/classroom_activity/57/Z3TWilbWZ5nPSgaf3iJ2BmSy.jpg',  'Arabic class in the Cotton Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'cotton-candy',  'art-craft',  'uploads/classroom_activity/62/DKsV51IuQRZcH4v5UXDGuWOC.jpg',  'Art & crafts in the Cotton Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'cotton-candy',  'topic-booklet',  'uploads/classroom_activity/55/isDw0mWNu5cTTA820yOZeXX4.jpeg',  'Monthly topic booklet in the Cotton Candy class at Marshmallow Nursery',  1280,  960,  0],
        [  'class_activity',  'cotton-candy',  'topic-booklet',  'uploads/classroom_activity/55/pPOtqaZQ0RXn4CypuzgT1TZ1.jpeg',  'Monthly topic booklet in the Cotton Candy class at Marshmallow Nursery',  1186,  1078,  1],
        [  'class_activity',  'cotton-candy',  'cooking',  'uploads/classroom_activity/61/Lib5XJMzJgqENum8a67yR12g.jpeg',  'Cooking sessions in the Cotton Candy class at Marshmallow Nursery',  960,  1280,  0],
        [  'class_activity',  'cotton-candy',  'english-academic',  'uploads/classroom_activity/54/dcXo4VWFOTziiFB4mNR1r7PW.jpeg',  'English academic class in the Cotton Candy class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'cotton-candy',  'events',  'uploads/classroom_activity/65/ylp3r4FxVrZfYW8ObDzZ7rRx.jpg',  'Events & celebrations in the Cotton Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'cotton-candy',  'events',  'uploads/classroom_activity/65/tLINSicTqjulyyn8L8c45clb.jpeg',  'Events & celebrations in the Cotton Candy class at Marshmallow Nursery',  1600,  1200,  1],
        [  'class_activity',  'cotton-candy',  'motor-skills',  'uploads/classroom_activity/69/0HGRgzuCEqVvnE7HrjlbNlDy.jpeg',  'Fine & gross motor skills in the Cotton Candy class at Marshmallow Nursery',  1280,  960,  0],
        [  'class_activity',  'cotton-candy',  'french',  'uploads/classroom_activity/56/MKN6KM034gCUk5iMYIqXCMub.jpg',  'French class in the Cotton Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'cotton-candy',  'garden-time',  'uploads/classroom_activity/70/BI8NsM0584eG5A7MWdhJhrSr.jpeg',  'Garden time in the Cotton Candy class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'cotton-candy',  'motor-skills',  'uploads/classroom_activity/69/zbhRDYvhzddIuaUmDGsOe5hb.jpg',  'Fine & gross motor skills in the Cotton Candy class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'cotton-candy',  'motor-skills',  'uploads/classroom_activity/69/jagMyF4dvFJ7vipj16XWZhrr.jpeg',  'Fine & gross motor skills in the Cotton Candy class at Marshmallow Nursery',  720,  1280,  2],
        [  'class_activity',  'cotton-candy',  'gymnastics',  'uploads/classroom_activity/58/0oxXBmmx2gvB6jrYvNszvSO1.jpeg',  'Gymnastics in the Cotton Candy class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'cotton-candy',  'music-dance',  'uploads/classroom_activity/71/ILCOHRUWqruYNJbb2xAupkhR.jpeg',  'Music & dancing in the Cotton Candy class at Marshmallow Nursery',  1280,  960,  0],
        [  'class_activity',  'cotton-candy',  'science-experiments',  'uploads/classroom_activity/60/o7IkDXCJysZpEsXkr6cnI8lN.jpg',  'Science experiments in the Cotton Candy class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'cotton-candy',  'storytelling',  'uploads/classroom_activity/63/s8xULleMYGkPBASEdz3M5szX.jpeg',  'Storytelling in the Cotton Candy class at Marshmallow Nursery',  960,  1280,  0],
        [  'class_activity',  'cotton-candy',  'monthly-trip',  'uploads/classroom_activity/64/Th0HMaCTG9UNG3MZrJHPZtOj.jpeg',  'Monthly trip in the Cotton Candy class at Marshmallow Nursery',  1280,  1009,  0],
        [  'class_activity',  'cotton-candy',  'monthly-trip',  'uploads/classroom_activity/64/SnsXQGx8nGyJvwF132bZUDDj.jpeg',  'Monthly trip in the Cotton Candy class at Marshmallow Nursery',  960,  1280,  1],
        [  'class',  'cupcake',  NULL,  'uploads/classroom/1/FGeJL5SJi3YRqYuWls0xqfyb.jpg',  'Cupcake class at Marshmallow Nursery',  1280,  960,  0],
        [  'class_activity',  'cupcake',  'topic-booklet',  'uploads/classroom_activity/72/L2enMHutllEage7BeY8mh8vX.jpeg',  'Monthly topic booklet in the Cupcake class at Marshmallow Nursery',  1172,  1078,  0],
        [  'class_activity',  'cupcake',  'events',  'uploads/classroom_activity/8/oYF6hJYOxmagBVCDB23fi7y6.jpeg',  'Events & celebrations in the Cupcake class at Marshmallow Nursery',  768,  1024,  0],
        [  'class_activity',  'cupcake',  'events',  'uploads/classroom_activity/8/7dm6172qO8KEpCeJKQqcVREk.jpeg',  'Events & celebrations in the Cupcake class at Marshmallow Nursery',  768,  1024,  1],
        [  'class_activity',  'cupcake',  'events',  'uploads/classroom_activity/8/34Ru9FXbrV1jQprHry7L6Ipq.jpeg',  'Events & celebrations in the Cupcake class at Marshmallow Nursery',  768,  1024,  2],
        [  'class_activity',  'cupcake',  'english-academic',  'uploads/classroom_activity/5/lBnSrnAMyJENmP1iSh0q6kby.jpg',  'English academic class in the Cupcake class at Marshmallow Nursery',  1004,  1024,  0],
        [  'class_activity',  'cupcake',  'events',  'uploads/classroom_activity/8/XlyX9EcaUI3rBdMgRAYVehfF.jpeg',  'Events & celebrations in the Cupcake class at Marshmallow Nursery',  960,  1280,  3],
        [  'class_activity',  'cupcake',  'events',  'uploads/classroom_activity/8/SIWE9bMAskO45tW5jHiYbGXC.jpeg',  'Events & celebrations in the Cupcake class at Marshmallow Nursery',  960,  1280,  4],
        [  'class_activity',  'cupcake',  'garden-time',  'uploads/classroom_activity/6/yxV2XCmTaHLKYEDYdhlZv4ek.jpeg',  'Garden time in the Cupcake class at Marshmallow Nursery',  768,  1024,  0],
        [  'class_activity',  'cupcake',  'garden-time',  'uploads/classroom_activity/6/ux2dGROIgFKuMfWM68x2z3iN.jpeg',  'Garden time in the Cupcake class at Marshmallow Nursery',  768,  1024,  1],
        [  'class_activity',  'cupcake',  'garden-time',  'uploads/classroom_activity/6/hKFfrPQFvRoSsI4QfKx8Bl97.jpeg',  'Garden time in the Cupcake class at Marshmallow Nursery',  768,  1024,  2],
        [  'class_activity',  'cupcake',  'motor-skills',  'uploads/classroom_activity/4/Xz2FBDy8ti30J7zq9x6pGDc3.jpeg',  'Fine & gross motor skills in the Cupcake class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'cupcake',  'motor-skills',  'uploads/classroom_activity/4/TUf1aaTLnlCfSszjjnGTnBuN.jpeg',  'Fine & gross motor skills in the Cupcake class at Marshmallow Nursery',  1200,  1600,  1],
        [  'class_activity',  'cupcake',  'music-dance',  'uploads/classroom_activity/2/1A0SL0Fd0kDXalu8WmQu5jGk.jpeg',  'Music & dancing in the Cupcake class at Marshmallow Nursery',  1024,  576,  0],
        [  'class_activity',  'cupcake',  'storytelling',  'uploads/classroom_activity/3/sL90oLzWzNUbqRbbWkfgM64n.jpg',  'Storytelling in the Cupcake class at Marshmallow Nursery',  768,  1024,  0],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/ufP0pEUvIyj48c4JI4f2a19L.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  0],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/ETpx7DwIShjiWevo2FYi6YLV.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  1],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/hNbdeqLGG1KKWfE9O4JIuom0.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  2],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/OPRcYTfb4Z6CdPEziID6ZNrD.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  3],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/el0ax9bnx0w1okubDBcmlv3O.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  4],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/mAc57CXfOZkp2crtjIatM5Lg.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  5],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/Avo0EFJpq7bnog2MQECwTmPD.jpg',  'Animals visit at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/odyXeo3MV9i1bjXUFoUBrh8W.jpg',  'Animals visit at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/Yi0kOm2zFPYnQa4QjWBcbXw1.jpg',  'Animals visit at Marshmallow Nursery',  640,  640,  2],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/87GrDXk3jNMF3FyPpSryYV81.jpg',  'Animals visit at Marshmallow Nursery',  576,  576,  3],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/NidzcZWjWdRDJGRtbD3c9Q9M.jpg',  'Animals visit at Marshmallow Nursery',  640,  640,  4],
        [  'album',  'animals-visit',  NULL,  'uploads/album/9/yF5Hgqgx7P12vgTWO7Kf2oE8.jpg',  'Animals visit at Marshmallow Nursery',  640,  640,  5],
        [  'album',  'circus-day',  NULL,  'uploads/album/10/EJLYgYYMJG5o2QDE6hFioTFL.jpg',  'Circus day at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'circus-day',  NULL,  'uploads/album/10/FhOLVZ7IUITOj7ifA1jUY5ts.jpg',  'Circus day at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'circus-day',  NULL,  'uploads/album/10/fS0L5c1AlgDOWjRoZDh1byFT.jpg',  'Circus day at Marshmallow Nursery',  640,  640,  2],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/keh4bHVfKY9iF6Gblb04QVme.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/QbdEw2hB6t1KfXmYDlrJitql.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/dhrFqgtuG0PnP98v8XKuVe7B.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1080,  607,  2],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/ZRRg4wBsNSst5sHFgCJJlhZR.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  502,  502,  3],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/6dcDMfTFZfwe1VXekxK3RvLC.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  366,  366,  4],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/2xLlNyBmoV1WbuNBnOeMp6WN.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  496,  496,  5],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/muK8JFQJHgcIK8kX84qYTy2m.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  488,  488,  6],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/oYrIbhhrlbHzvAm0k3Wm4UBs.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/9kaOeeOqHHyOXAgo7QZgCTLl.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/U149YNEghk8pgTHKoeXaZM4o.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  640,  640,  2],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/CEVvvmNcFtzTgRZQGJXZ3y8Z.jpg',  'Solar System Competition at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/ZLDVrUmf5VQAmAfz4KKEXNri.jpg',  'Solar System Competition at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/u9IvacIwO82rvA1au5BVkio7.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/khlwOgV86O5NW900crxtavF1.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  640,  640,  1],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/7tiMyrr2wiWnVvjlazbp9JYa.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  2],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/wggO9fyiSgLtTIuEUdbfBaEY.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  3],
        [  'album',  'trip-to-dolphina',  NULL,  'uploads/album/6/h6Gua4iFZxdGmmZmvmkTkvRP.jpg',  'Trip to Dolphina at Marshmallow Nursery',  640,  640,  0],
        [  'album',  'trip-to-dolphina',  NULL,  'uploads/album/6/akmy5U82AiNRciH7WP7rRrm0.jpg',  'Trip to Dolphina at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'ice-cream',  'arabic',  'uploads/classroom_activity/33/9n9j1Tpvjn44IAE0GUEbPKws.jpg',  'Arabic class in the Ice Cream class at Marshmallow Nursery',  576,  1024,  0],
        [  'class_activity',  'ice-cream',  'art-craft',  'uploads/classroom_activity/38/bkpCpfh8cSsn7BZKdUIQWCaf.jpg',  'Art & crafts in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'topic-booklet',  'uploads/classroom_activity/31/ecRx5lcEZpyicMXojIQE9qCF.jpeg',  'Monthly topic booklet in the Ice Cream class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'ice-cream',  'topic-booklet',  'uploads/classroom_activity/31/B4PyU9VabEKjinMrlrNO1KWO.jpeg',  'Monthly topic booklet in the Ice Cream class at Marshmallow Nursery',  1186,  1078,  1],
        [  'class_activity',  'ice-cream',  'cooking',  'uploads/classroom_activity/37/t4iJrOGN9HCo0e9l5SbCbePE.jpg',  'Cooking sessions in the Ice Cream class at Marshmallow Nursery',  1024,  768,  0],
        [  'class_activity',  'ice-cream',  'english-academic',  'uploads/classroom_activity/30/UsHbE08yqTGaeSMgmKJ8sIDU.jpg',  'English academic class in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'english-academic',  'uploads/classroom_activity/30/b3gqbhBhru8EzMObu2nMv7I2.jpeg',  'English academic class in the Ice Cream class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'ice-cream',  'events',  'uploads/classroom_activity/41/7sSCi4vhakgVRvFy5gbigFsb.jpg',  'Events & celebrations in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'events',  'uploads/classroom_activity/41/UEay5rEwucFlmuZKpLyMEh57.jpg',  'Events & celebrations in the Ice Cream class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'ice-cream',  'events',  'uploads/classroom_activity/41/rmZ1b510J9ja3qqDZ71nVq7N.jpg',  'Events & celebrations in the Ice Cream class at Marshmallow Nursery',  640,  640,  2],
        [  'class_activity',  'ice-cream',  'motor-skills',  'uploads/classroom_activity/73/sJvBTOvS0g5yjzdnaCpyAxCD.jpeg',  'Fine & gross motor skills in the Ice Cream class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'ice-cream',  'french',  'uploads/classroom_activity/32/dW4bZ3P7qApNEoBrs8A2w07r.jpeg',  'French class in the Ice Cream class at Marshmallow Nursery',  1024,  768,  0],
        [  'class_activity',  'ice-cream',  'garden-time',  'uploads/classroom_activity/74/KCYHnnoZw215E5c2L132VK2w.jpeg',  'Garden time in the Ice Cream class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'ice-cream',  'garden-time',  'uploads/classroom_activity/74/2DfPJABJB2qIfUh2p8XxXuSg.jpeg',  'Garden time in the Ice Cream class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'ice-cream',  'motor-skills',  'uploads/classroom_activity/73/qLbaiWSBAak0eloRaYwslAjw.jpeg',  'Fine & gross motor skills in the Ice Cream class at Marshmallow Nursery',  720,  1280,  1],
        [  'class_activity',  'ice-cream',  'gymnastics',  'uploads/classroom_activity/34/KdGJJOb58UWQf8eUaDBxdYvF.jpg',  'Gymnastics in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'music-dance',  'uploads/classroom_activity/39/7EIElPJZmvtYPcxnZNtG2vv9.jpg',  'Music & dancing in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'science-experiments',  'uploads/classroom_activity/36/3myQ5il90BHh6ou14hxFE5rj.jpg',  'Science experiments in the Ice Cream class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'ice-cream',  'monthly-trip',  'uploads/classroom_activity/40/8FcteNIRNjYQu4FMaIW9uCX5.jpg',  'Monthly trip in the Ice Cream class at Marshmallow Nursery',  1024,  576,  0],
        [  'class_activity',  'ice-cream',  'monthly-trip',  'uploads/classroom_activity/40/ND8LDf9UgILBMc00KAw69OmI.jpeg',  'Monthly trip in the Ice Cream class at Marshmallow Nursery',  1024,  768,  1],
        [  'class_activity',  'lollipop',  'arabic',  'uploads/classroom_activity/45/bJ12l8JKmedy1uUBsTQisAY6.jpg',  'Arabic class in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'arabic',  'uploads/classroom_activity/45/n1cN0XsFzqq1QSjWRJTZz2Ok.jpg',  'Arabic class in the Lollipop class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'lollipop',  'art-craft',  'uploads/classroom_activity/50/rteoPK6cIhuDT6YKRikC3oIj.jpg',  'Art & crafts in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'topic-booklet',  'uploads/classroom_activity/43/KknjVvgbQbGeIS7bAzoqDgDz.jpeg',  'Monthly topic booklet in the Lollipop class at Marshmallow Nursery',  1186,  1078,  0],
        [  'class_activity',  'lollipop',  'cooking',  'uploads/classroom_activity/49/vn5W7i0V8GbzNuJZsTLRDzCE.jpeg',  'Cooking sessions in the Lollipop class at Marshmallow Nursery',  960,  1280,  0],
        [  'class_activity',  'lollipop',  'cooking',  'uploads/classroom_activity/49/45HzFFmLhtx1IoV5NmgV9Lgt.jpeg',  'Cooking sessions in the Lollipop class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'lollipop',  'english-academic',  'uploads/classroom_activity/42/ZVntXOzsSM4oTJr2gaLABFFh.jpeg',  'English academic class in the Lollipop class at Marshmallow Nursery',  1600,  1200,  0],
        [  'class_activity',  'lollipop',  'english-academic',  'uploads/classroom_activity/42/hCDvNl9UUM15CtgoRpamcRrh.jpeg',  'English academic class in the Lollipop class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'lollipop',  'events',  'uploads/classroom_activity/53/Iyzl4X4kt1Bvc1h5Hdc65DAI.jpg',  'Events & celebrations in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'events',  'uploads/classroom_activity/53/WnoJQRfwD3LYZ9qZYbFpom8S.jpg',  'Events & celebrations in the Lollipop class at Marshmallow Nursery',  640,  640,  1],
        [  'class_activity',  'lollipop',  'events',  'uploads/classroom_activity/53/MVhWVoDn4gfvQewk8gcJ6aao.jpg',  'Events & celebrations in the Lollipop class at Marshmallow Nursery',  640,  640,  2],
        [  'class_activity',  'lollipop',  'motor-skills',  'uploads/classroom_activity/75/9QcswIt4yTtPeYCPsSeD7SpR.jpeg',  'Fine & gross motor skills in the Lollipop class at Marshmallow Nursery',  1330,  1600,  0],
        [  'class_activity',  'lollipop',  'french',  'uploads/classroom_activity/44/BmEnw8IaGnz6Dd9SxRaQmeq2.jpg',  'French class in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'garden-time',  'uploads/classroom_activity/76/V03qhxSyteEDpEfu17cjbXY9.jpeg',  'Garden time in the Lollipop class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'lollipop',  'motor-skills',  'uploads/classroom_activity/75/4ZAVRfsRNLxFwpJZQ7P4rTms.jpeg',  'Fine & gross motor skills in the Lollipop class at Marshmallow Nursery',  720,  1280,  1],
        [  'class_activity',  'lollipop',  'gymnastics',  'uploads/classroom_activity/46/88sFBQFiFgnz4qQm5GJcFol2.jpeg',  'Gymnastics in the Lollipop class at Marshmallow Nursery',  1200,  1600,  0],
        [  'class_activity',  'lollipop',  'music-dance',  'uploads/classroom_activity/77/f5ahEUk9dXjkyH6jNxvZwLAQ.jpg',  'Music & dancing in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'science-experiments',  'uploads/classroom_activity/48/AKyQBEObx8jHXzRMbie3ZtL8.jpg',  'Science experiments in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'storytelling',  'uploads/classroom_activity/78/BGVjXeGZcuKcQ05CaAirxLIi.jpeg',  'Storytelling in the Lollipop class at Marshmallow Nursery',  960,  1280,  0],
        [  'class_activity',  'lollipop',  'monthly-trip',  'uploads/classroom_activity/52/nau526gDCapMX9WK5PyYTH71.jpg',  'Monthly trip in the Lollipop class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'lollipop',  'monthly-trip',  'uploads/classroom_activity/52/E09sHLETBSRnvryPT8vyabPC.jpeg',  'Monthly trip in the Lollipop class at Marshmallow Nursery',  960,  1280,  1],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/DrnFA6YZ2JpPbkJq4guOHSqj.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  0],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/6PZUA8UFXjK7sbtpdmKX3zwv.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/e9ndBcNad8B8YuIyH3C53qao.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/WAf0wk46xPo3Myg0kGVuDhsb.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/qNlxDxUozZYK9uoCyy6q4euf.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/34wvvJ3DOcga9L9lgyrzkZHx.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'parents-reviews',  NULL,  'uploads/album/12/JRzCvtSckqXUoTkD3xxpioOY.jpg',  'Parents reviews at Marshmallow Nursery',  1080,  1350,  6],
        [  'class_activity',  'popcorn',  'topic-booklet',  'uploads/classroom_activity/79/RLPTQll6X8znpTZcwqGZ5UOb.jpeg',  'Monthly topic booklet in the Popcorn class at Marshmallow Nursery',  1180,  1078,  0],
        [  'class_activity',  'popcorn',  'art-craft',  'uploads/classroom_activity/14/NQ1N3mN4zFepaFjaNpZCOKg7.jpg',  'Art & crafts in the Popcorn class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'popcorn',  'art-craft',  'uploads/classroom_activity/14/MQ8dWfyCxbndsxwUesZqHFBa.jpeg',  'Art & crafts in the Popcorn class at Marshmallow Nursery',  1200,  1600,  1],
        [  'class_activity',  'popcorn',  'events',  'uploads/classroom_activity/18/DPOxbnsGAOryv4bJ332Ki3M0.jpg',  'Events & celebrations in the Popcorn class at Marshmallow Nursery',  640,  640,  0],
        [  'class_activity',  'popcorn',  'events',  'uploads/classroom_activity/18/BLYLJmNK8oTL3NMvmEc7kbrk.jpeg',  'Events & celebrations in the Popcorn class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'popcorn',  'motor-skills',  'uploads/classroom_activity/10/jf9sdi4LFG0KY4yNnuoSEe6C.jpeg',  'Fine & gross motor skills in the Popcorn class at Marshmallow Nursery',  1280,  720,  0],
        [  'class_activity',  'popcorn',  'motor-skills',  'uploads/classroom_activity/10/4zLpyFAJ8hEWY8H9kJjXsFWC.jpeg',  'Fine & gross motor skills in the Popcorn class at Marshmallow Nursery',  960,  1280,  1],
        [  'class_activity',  'popcorn',  'motor-skills',  'uploads/classroom_activity/10/KJOqB3yNb5pRzaWOiBIC1nDQ.jpeg',  'Fine & gross motor skills in the Popcorn class at Marshmallow Nursery',  960,  1280,  2],
        [  'class_activity',  'popcorn',  'gymnastics',  'uploads/classroom_activity/11/XXQH1gO9Y3z50yEGqT6vLFU1.jpg',  'Gymnastics in the Popcorn class at Marshmallow Nursery',  577,  1024,  0],
        [  'class_activity',  'popcorn',  'gymnastics',  'uploads/classroom_activity/11/LalIhWpRLq0VmZFWl82pmt4c.jpeg',  'Gymnastics in the Popcorn class at Marshmallow Nursery',  768,  1024,  1],
        [  'class_activity',  'popcorn',  'storytelling',  'uploads/classroom_activity/15/u4XQldfejZlvuEmGlYSpj33k.jpeg',  'Storytelling in the Popcorn class at Marshmallow Nursery',  1024,  768,  0],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/orHFigT6oXDlWNK8IAfKGHqr.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1640,  624,  1],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/uJGIyw44kjiH6fKBaktKHtPO.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  9],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/ybsR9w3WGmr4LLlyzmQ748bO.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  17],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/pQcNDppEcK9atksAjkceJuUy.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  26],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/lMYHin3sh0ysKpCKF2pcp2AC.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  34],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/AKDnMcTED7WsAJBxK6Gp0lGf.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  43],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/SXvmo2KyWlzxo2X9Ka3tuaD8.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  51],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/j5Xhh59HtSYkL7Nz1z3dTEqn.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  60],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/zoeaMN587HGnEbHp2RmMlvb9.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  68],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/R2uD1bj3vGurt2JbllQXhqO6.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  77],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/4Pz8PAFgUMynp8idje4GSXW3.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  85],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/xlfoCOfswPSbiIRJSHOk5IzF.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1271,  94],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/HEAlJOqTbddpuLhkm2dcZx3F.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  102],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/C4OWnJHgRDKOXY3ZLet8zMAu.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1280,  1920,  111],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/NMzHJtN0cnoTnq6LA6bwizkV.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  119],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/Eo2eVv73lNLrtTg9MteYLMEP.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  124],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/qD1PnYPj4X5VdbFKkSY8Y2B5.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  126],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/mOboFXTzRD30QqL1SsddQ00H.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  128],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/1N1nRlmQnOkivKKYWOFAD2Vf.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  130],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/5f2j0REmjGojwPQMSsa6sL2N.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  132],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/mCH9jH4CCLYGRbAIXjsPiWC7.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  134],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/jMPijZZlEXkpbcI2vOLgY89B.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  136],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/k1JKi04Ym9K7YMzLn9uvhtm8.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  138],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/74HOtli4UzJ0vXmTzCKUgUNn.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1746,  1164,  140],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/Ed7W0eFmq3k2WJ0MFOHSqrGE.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1749,  1917,  142],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/1EJWD1MpDplIWBgNjYmTV332.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  144],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/FzWd3FZbOX46H3mXfp7TwfK9.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  146],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/zoy2xwldgbTfbJtixdv4vl9g.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  148],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/XmNlnvjraZKNItzJUzXO8Xmq.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  150],
        [  'album',  'pyjama-camping-party-bedtime-stories',  NULL,  'uploads/album/3/T38cr9etc0aLCrRx4kNGfIcZ.jpg',  'Pyjama Camping Party: Bedtime Stories at Marshmallow Nursery',  1920,  1280,  152],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/dZYAZhzZN4XbOJHnuy2y0MMk.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  2],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/IQDv7qfcV3HMHgAnKLyMHyXe.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  3],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/F7Zv346Pq2gC5onVBaZeHCAG.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  4],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/7ysQycZ07VC1M6nFJTxxZpPj.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  5],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/OghlhBJaoIKS7vGcJgMRliqv.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  6],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/YkZlYSXDcH7TlwioDkzqZw6Q.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  7],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/9XWX8Tw6oxkxI4kGMKVhguYW.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  8],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/9w3U39ipbiHi0McZSaY0x0YQ.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  9],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/CGEyqNanP64fNjrB8RBiUgyX.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  10],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/oaIemzg71s7C9ZdLTJtuQdZU.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  11],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/kqZJ7S7djDxykg30QkSCwTkL.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  12],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/WxxQEqEJWgnaBRPOnkh3xMTx.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  13],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/1d6wZeD2Py4K0RMKDQT9Jlar.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  14],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/DABmNJIc0SWEUBHX3R6CPEVI.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  15],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/C8G9gOsGC5ARnlTUPZmOCFnU.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  16],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/3821SfcHa8jpeOgg1leCA0yj.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  17],
        [  'album',  'solar-system-competition',  NULL,  'uploads/album/2/wnBBLbHZSTveaS9irXKCA8jX.jpg',  'Solar System Competition at Marshmallow Nursery',  1080,  1080,  18],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/Nxuwn5bGc5SMmT8cLEDLBJoc.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  6],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/Z9A6BySxmbU5d00zOTmkaf7d.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  7],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/4PpUaVoOuMaQ7nhrC5X15yLG.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  8],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/4VIB3mY3iyRh4DR96w373ijJ.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  9],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/SMRe0CDZwu5l5DZnkAavql6g.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  10],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/jRCibrQM6h0kOVthena9paJ8.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  11],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/s2WuMn1ShjUGw02WF7ZIl8VA.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  12],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/sVOU6X0IDHDm40asFpfEyX2L.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  13],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/AGdX26AFVhZQtoKBn4CU5b9L.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  14],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/2OOGTDbHVQa7TA31cDvhIcI2.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  15],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/hqWE3pIfdzAmVluOzaGtwk58.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  16],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/bU6trkEPim1d4TFRQXmfOAjz.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  17],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/u6NSeINTljfZzTTIsN5WmVD1.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  18],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/rX95T25deZYCUHOFjOOWPctp.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  19],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/MYq69rv26ME0h9YRGE79L93P.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  20],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/7MyO8bL9FDvjqnoEtUUHYPEZ.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  21],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/BHQFvKtvzvWsJcJUnmYJAvrF.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  22],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/2XJvLVeRNykATcdAxffRLQwk.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  23],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/6jPlW9s1M4fvthokZyBGVJ9v.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  24],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/nRgqSHGCTLcIMJJWh7jzsAjA.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  25],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/4u8ShnJ73J5754eH0REkvdXU.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  26],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/NMkIDgerNctPBAuildOhPyow.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  27],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/jEGi94hH4FH3Z6LGkTPX3VXo.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  28],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/lQ5tWJN8z0F9zv0z7gscNaGz.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  29],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/HEFRRZfKZX5ZamgCgsqgOKld.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  30],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/LKxZB1OZWHkMNsdcpqJT29zk.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  31],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/IR9kPdo6fs9hwGYzpeDw8NuC.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  32],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/oNyRDIOILOx1uY0eISvFN3xZ.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  33],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/7XwbH0hz6g7lnJKDca2xVHcy.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  34],
        [  'album',  '6th-of-october-celebrations',  NULL,  'uploads/album/4/L3enByLiEGK0HiC2YFeOabdx.jpg',  '6th of October celebrations at Marshmallow Nursery',  1080,  1080,  35],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/18iqOSviyKYcVRbx0T2fdvLK.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  852,  314,  7],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/tbiPj4u5DagUxm7ebgLyuKn0.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  8],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/cCohleccuIVzlkFTbAusCh1h.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  9],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/vD4eBkdKkQuGOGaYZGyWEdii.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  10],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/uEd5gApb5x8zpfN8bNXsnYp9.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  11],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/UrOSuRj0GRa3GlHGnFV2ruE4.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1447,  1920,  12],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/ZkxEp1GbRFEAtyzAquZBR6j7.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1447,  1920,  13],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/uxZGBaiC5bOetdDh53wuOGO2.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1447,  1920,  14],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/TuU1khAYYhPeSqxzcOFZOAu3.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  15],
        [  'album',  'graduation-2026-under-the-sea',  NULL,  'uploads/album/1/zd5M6wqpIvll7mJ0WveaWJJW.jpg',  'Graduation 2026: Under the Sea at Marshmallow Nursery',  1448,  1920,  16],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/WW2pXe53MCv2qWqPcL29J6Kh.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  4],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/LWupndKr7i6kt2Tecd5CblJt.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  5],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/G8DFVhhSAIKOguOluryJkPRE.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  6],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/OjmSxTZQtsj9CNAlHDixyWtd.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  7],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/LYjc5vYjQ9fWswAr8eVETydy.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  8],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/lK9IVphznqvY1TcVBoDIfRYt.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1200,  1600,  9],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/Cx5vJs3rakvg09M1aoRGAHws.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1086,  1448,  10],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/zIp1rFhEqFZpT2VaJFuawsvT.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1080,  1350,  11],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/djH3TnHdSq4cpnYCbwLRxTRu.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1080,  1350,  12],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/6ocb16zlcj11o6lbqS3IBcm6.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1080,  1350,  13],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/gNwwslNL6ZAS2LBxsL5TvElm.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1080,  1350,  14],
        [  'album',  'summer-camp-2026',  NULL,  'uploads/album/7/n0jNm3OtMEGncGuOTMOiPaR1.jpg',  'Summer Camp 2026 at Marshmallow Nursery',  1440,  1920,  15],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/jAG3SsHgBFq3UDAIYT9nxc7E.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/cMcAR9kpyDTV398cuxDLgkSe.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/CCCJ5XNxw2XFHzop8RHthWz8.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/z5RAt1KgW94qQAHrIcpWsddO.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/twGlBafhfjb7BMXrPDW3FvLY.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/sZzka5XaM3Hb38pHY1AoEAZd.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/EkqpSMyVyHCZXHddQgzzbfFz.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/sHPV1W1oQ6iF9FHC6rYit1nO.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/3MWiVaoaznLpggldx4mbmhLR.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/GGtDtHTUcxbL9IHWezgMvhpM.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  10],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/evNTcHPQKRSa5nOXfflu9eCj.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  11],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/ZrSjsKtoeuAG6d2jBtVdubuN.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  12],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/f23biGlI7PzA1GbMmGrPSYpL.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  13],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/mxXM7zNriGiXJ5SYk6xFCVNS.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  14],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/u585gFeiZ3rqhN8CVCZ2gcfU.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  15],
        [  'album',  'winter-camp-2026',  NULL,  'uploads/album/13/8nIQZHxCa7NbfYJE7Tsb1tJL.jpg',  'Winter Camp 2026 at Marshmallow Nursery',  1080,  1350,  16],
        [  'album',  'spring-camp-2026',  NULL,  'uploads/album/14/ocu841pTivtCikswlqFmfXoi.jpg',  'Spring Camp 2026 at Marshmallow Nursery',  1350,  1688,  1],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/JVVcyyImTJ6fkOLDUB0miRKb.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  3],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/BefWxPogHFCVENLx1sO73R6x.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  4],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/7TvQVKk1t1E6SFbiGvnsfzVV.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  5],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/Y1CE6BvPsySSzFFRwMOKsU0X.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  6],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/hBVoUjNqdoKIiLbwueC7YPJj.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  7],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/mN8riNA4iLNp1OCajVjDfFHW.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/08sA1BcpaBaB70orybGdhTvQ.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/w2a5hs205MNWCaMNjTF9kXmM.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  10],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/cKsn1PiKzIPKhGwizgYMOwHY.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  11],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/ltVFvvSFvasEq9OYnuhYTQFl.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  12],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/SnxZRqaQddQSRMJhaQBei2Ji.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1920,  13],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/auprA48Et82j12RwwlKEOmio.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  14],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/U1lCPghB9YuPkSW0fjSzOOxZ.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  15],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/wP42mLCTQvnJtUmctBIUtss1.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  16],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/agXVw9iDuMMckNC3jfZqktUp.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  17],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/39R3D5MrjaWIUOtvOaMdz4MY.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  18],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/YjPMGOtNT061ZPKdM0VKRvDw.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  19],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/v9vsFkaYmqCMMCXS6xdLGKCx.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1635,  20],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/px0GDJZtZ6fzNEfYvqU1wnjt.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  21],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/bdHUA5qJEFeshunZQWdJnes5.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  22],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/27Biy4RfztPJCaxeMuPp10YF.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1635,  23],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/wIczPjM7eF3OkXhpzHLGKlhB.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  24],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/RruX3N934icZv24P5RBKzhoh.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  25],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/w2nUgTtzoFffP2RXbhX2oALS.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  26],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/ZFdJ0ck5i8iVYTSzPUtk69b3.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  27],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/7gU6IxUvKupH6p4TDLlvlGwv.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  28],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/WE1bs6JlAb5DrwKlFmOtmyRl.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  29],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/WERZDxdWovzdACRgoahP14dU.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  30],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/XpgYziHXAA5kC2niCw2SR5br.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  31],
        [  'album',  'marshmallow-schools-expo',  NULL,  'uploads/album/11/0NFwlSc96zHumMAAWNNTXRWc.jpg',  'Marshmallow Schools Expo at Marshmallow Nursery',  1440,  1640,  32],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/geyry4QthHffSNf2E9UXkuRm.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/hbV0aSMhhFuD6RfAdoLL34PG.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/OR3pcmYKp0K0HUpbdKOn5qdm.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/bI6oVhVBsETTaV19gWxzxNIm.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/7oTOa0PfVqSFwjnDMk5Dw9vL.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/pEYefTewV3MIK6f4dK1blmhc.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/3s6qK1WYHMJA4WCBOiR1C22i.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/8Q8NYDu6zd09RbRKRAniksAT.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/9TCmqvxS25xmp7zQYyLODtob.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/egRz5qJQpG2ukqll6i3xDf7b.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  10],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/H0g8oHrDLXagNUainfrMNta1.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  11],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/GVNAv7CWrBWfwTSKCdzo5p9s.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  12],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/P1X09Kxmw7oTpNeqArLzEQSh.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  13],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/8bdrICeAUpTS0eQBIkFX8DbL.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  14],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/aavFJTeMG3uSLmMUvZZ6SsTp.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  15],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/mRxvr6UYlLf9ZeMdq0jI7ySX.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1309,  16],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/g5iLmN4c0UkVNX56jq4KIuz0.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  17],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/tWevQHpu2vFwRQTgiqBDwf5G.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  18],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/82S7Dahe0lpPipzbFPQgnAvv.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  19],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/bth0zSKuwATcMIdJBiTX6slG.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  20],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/HI3oHykSAI5a53n1AZsQi0xN.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  21],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/BI9yh6H9IoRpvfU9FCxrhPUk.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  22],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/CwTO5TxCG4hD69gKRbBlj56J.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  23],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/J4epXcZpxdmTzQI0xzwNXPhR.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  24],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/xjmAfmsWVGAcEFm2L2ee23DF.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  25],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/Q3EEl8BwwEPe85zR596cZuMh.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  26],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/oHBxJKyh8skp4gH6GyVqmzyt.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  27],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/r3D3nEwPf8f2bxOw4ceRpcuj.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  28],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/vKuCzi1GA91ZLYmxJyoO3bNK.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  29],
        [  'album',  'halloween-2025',  NULL,  'uploads/album/15/lTG9gxE0dkYUbj0XJSkcg7ol.jpg',  'Halloween 2025 at Marshmallow Nursery',  1080,  1350,  30],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/OLlHI4z0k6XkVEZEsBrl69rU.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/rxGr4JUbQ23PT4wWU4pnZiN0.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/6Dx3laoFYqalzp2cmYZDpLlP.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/2uekhWDDsJb7afLkTUOdMdI0.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/jRsrU91tKg8zu00PUjtBv7up.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/8MhNF2RpcFJd9nKpeYRJ8YZY.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/gaxTwAiQC5va8g6Y2bzBQThN.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/30uN2QfVDcgtMTp2t0N811Kp.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/aLt6ScZYRW7o6d7INf6X66cP.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/gDm1ywhdBanT9eHLKUagsMhZ.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  10],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/Rd53Zx6UMjZrtDUI18MkdXHm.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  11],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/sw3P8lqBMco4xCh3efFsNP0p.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  12],
        [  'album',  'occupation-day-2026',  NULL,  'uploads/album/16/hdz8PdtXSTeAXzOKwDKqkIEX.jpg',  'Occupation Day 2026 at Marshmallow Nursery',  1080,  1350,  13],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/me4sYIPRJV5C0fAPFhjOn4jm.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/snefaFgxT3mAZ1fOKRjDUy2x.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/EOP9VRtG8t5YYmzQfd5CEDff.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/K7RTikFnXjpi4ojZnSVsoQF1.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/dcn5ruUFFjPX9p10HmVywFKO.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/TXHwk8HiXaZg22TDIHQLoDFP.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/reW8vm4mRjLInBNUhr6QftyH.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/zIRuOZPhlPi18KZnMjbRkUPD.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'space-event-2026-fikrymo',  NULL,  'uploads/album/17/L02ju3YTI3CfrsNWPQv0JiO9.jpg',  'Space Event 2026 (Fikrymo) at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/W1AVF41xyCR3nePASchr1ZUw.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  1],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/tq7E5equdmSnprlrnkumWKaz.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  2],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/XOI7pLiwPbHdAiBst7TusUvq.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  960,  1280,  3],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/zq2wFDkzyjSKtxdUpWvpU0pQ.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  960,  1280,  4],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/wRGJoj95uvttWbWEBW1ViE0o.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1280,  1703,  5],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/Mmdnbs84V7Gc9K3PqEy9l9M7.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  960,  1280,  6],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/Ni4aAGatS1l1amDy5fZZ76xr.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  960,  1280,  7],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/rHQvRRT1q4deXmTRmi3Z8v5s.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  8],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/6IZeRgLjjsUvS2UHNgfdFaHj.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  9],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/4tNamyOuZwVqxuXGTQvLrLR1.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  10],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/ST6avrtye6eKdLKckKUt7WUy.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  11],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/xje7gWsUESm9DN1Qe2a3nsiU.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  12],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/CemvBztdqJfYAtERJAL0zq2z.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1440,  1920,  13],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/kPP3QIuJE0MVrCQjkC5SSyjX.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  14],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/6QZiRVxC7JK0mUmFKwtRug2r.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  15],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/HPTkrGqZUftiKsAqY3pZYu19.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  16],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/qKRz7X2dvhRsrla3vAAlLjlo.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  17],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/B4ueCNbW3LyKN4paes7gOVhU.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  18],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/KUfvk0pBWvHMeXJm9W6BrlMU.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  19],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/KX56AcNFSdBPlgFDZpzDO9OL.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  20],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/uEynXgb2MjgbGhoa9rvCE5C9.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  21],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/q4ZXDq510UoUK0dYE172nWju.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1443,  1920,  22],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/5kAMiPbfLGDP1ExoemYXunCh.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  23],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/4PF7KWiB1KQxyEdzxQtTuwa7.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  24],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/I9DGPFTqhzf0cCfWkMGIFM5c.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  25],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/XIltgwcyhPBp6jkWxOTyF1RO.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  26],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/xrgkLqwBRwjuHSEXSF0cTROk.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  27],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/DN2e7lIW7ck8wmiXOxyXVyGz.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  28],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/75sjLhnayNDsfmwPdOoGP2rh.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  29],
        [  'album',  'fathers-day-2026',  NULL,  'uploads/album/18/B2vyU98EqXPDv7lO2WmdEeHs.jpg',  'Father\'s Day 2026 at Marshmallow Nursery',  1200,  1600,  30],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/Ew13j9wJhCNFxtE4g2FP8XET.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/YK1kbTv31lLr0jxvPnRBj2tX.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/Q1yHJqUOF2FbhetKCrKohJRc.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/VH8lU54L2neQmxg4iWnRKFoB.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/zWnt6iz5bIsUHN75kRfIehfs.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'eid-al-adha-2026',  NULL,  'uploads/album/19/V4oKx7juVYh9xfKPCZrIpmx6.jpg',  'Eid Al-Adha 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'eid-al-fitr-2026',  NULL,  'uploads/album/20/hsDPCVPSqEZXM2PhftoHZEZV.jpg',  'Eid Al-Fitr 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'eid-al-fitr-2026',  NULL,  'uploads/album/20/wvVsXyLgAugVKhuTHnQ8OAzf.jpg',  'Eid Al-Fitr 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'eid-al-fitr-2026',  NULL,  'uploads/album/20/8RJ36NjQbVklCuD0VZYuMDol.jpg',  'Eid Al-Fitr 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'eid-al-fitr-2026',  NULL,  'uploads/album/20/OQNZxKl1wQ2Tr1JQmYy9Sm16.jpg',  'Eid Al-Fitr 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'eid-al-fitr-2026',  NULL,  'uploads/album/20/9s9AfZHWzcYTYwUdnwjah8Jp.jpg',  'Eid Al-Fitr 2026 at Marshmallow Nursery',  1080,  1080,  5],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/lssCX5dyNzR4b481VmCDsktN.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/LhUl3XTA5QSzWraAxWQAeYG5.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/kdsJaugbo2pf3yeKSIwSvQ1H.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/0jMso53SLH1FTftEEnQANx7i.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/MeS1IW4s93pHONh5z2ZhJjwj.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/1XTwpxsz4kpM6trB7nDm6zBG.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'ramadan-2026-suhoor-with-moms',  NULL,  'uploads/album/21/TlXOMGjoVorLacRZt6cScqgo.jpg',  'Ramadan 2026 – Suhoor with moms at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/csgua5LW1ygeATxw1xSsp4hQ.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/LjLzjeDEDZy5y3aOoYXnVeQr.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/2OQyl6F2IczjOE7ygovUpBHS.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/tDfIqYqlRKKIIu2BEiJZsOFc.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/WL3W3EDbh7beb3qjgaLCOYQB.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/VNFyUxCxcKGVuYsp7KxF7xAI.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'ramadan-2026',  NULL,  'uploads/album/22/yXfozInQvmbOnKnsATPI7pZ7.jpg',  'Ramadan 2026 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/0iKpQmqEcyYprbOxGUAu7bbJ.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/12WmbJILMoO3GO1TZhyArMeI.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/8QMYA8cL7toCmY2qGfY6Nq1L.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/7MCbl0RI0Xykx1NOK4KuX3sg.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/PbPQSv8lQ2vqWuFLAwXiswo1.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/ogjej099utAYtwhyD4sdkAR9.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/g57OuuqBL6N3fQQRjEsj5dfu.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/OF0DigMIk0KcKeaVCTJo8hmP.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/yYjjr846Dxu6Th0UBNtgRIgQ.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/6uL0eZLqanMpzrSxRRQkyMES.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1350,  10],
        [  'album',  'easter-sham-el-nessim-2026',  NULL,  'uploads/album/23/hOFnEWhahstOcO3K8Dgo5Dnb.jpg',  'Easter / Sham El-Nessim 2026 at Marshmallow Nursery',  1080,  1080,  11],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/kGHoiWIfOkd11G6o9TzH7K9O.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/wu8LBI2MaFkSNZSrS2tER0SY.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/Oct8UT7OENTnxBYzZGpBd3OZ.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/NxcVPGUpNiVrU8ilAIW2MuLP.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/tl6HMx8KOyz7mzU60Nb8xdXD.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/3fpf0Hjiue2GJaIoVwsZVeso.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'wacky-tacky-day-2025',  NULL,  'uploads/album/24/1tR3fJVk3Fl7KeJteWLKJ51S.jpg',  'Wacky Tacky Day 2025 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'back-to-the-80s-party-2026',  NULL,  'uploads/album/25/yIWuRPvDkRMD6LzlO4DID471.jpg',  'Back to the 80s Party 2026 at Marshmallow Nursery',  896,  1194,  1],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/D3M22QQmieMAANkOskMb0zcd.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/iaCUARgIIT1Ev3cLTjokP52F.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/MtpByn9YFNRVcTXI5lU0s9Vq.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/yG6tGvbT4WOE5v2LDlpqe63H.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/tyiR4kfEttn5gGnVXuaX6pCc.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/2ClgEsXY157c4ltlNITyeNwr.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/gmafbqvwMXsWlmBtBsadWC3N.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  7],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/Nc2UyNi1FjbboZCwBtsCr86I.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  8],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/WdPuSNSi80dkQJNdHq98eWXs.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  9],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/MaXqBLXOh0kr1DXceg5S4pbb.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  10],
        [  'album',  'trip-april-2026',  NULL,  'uploads/album/26/xSCjJom4inm0Wt1ALwLazu2z.jpg',  'Trip April 2026 at Marshmallow Nursery',  1080,  1350,  11],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/Vl2Xf0mNk7EqRAi60OlSRpIT.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  1],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/ctR7Otzj2j51q5qdCtoGoZx2.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  2],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/f3qCYbYC0iVXjsu1qQvClDj4.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  3],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/dd2iwzT1fEBEtd42INDU5aPi.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  4],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/r2w2G1UzCsdw562TxF9hddDL.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  5],
        [  'album',  'trip-january-2026',  NULL,  'uploads/album/27/LbKEVGjT89B19PcjAbCKCWza.jpg',  'Trip January 2026 at Marshmallow Nursery',  1080,  1350,  6],
        [  'album',  'first-day-of-school-alumni-cards-2026',  NULL,  'uploads/album/28/DhowTd6yYCOYn8irqkFAvlCt.jpg',  'First Day of School alumni cards 2026 at Marshmallow Nursery',  1440,  1920,  1],
        [  'album',  'first-day-of-school-alumni-cards-2026',  NULL,  'uploads/album/28/B4Q2A8yXtpBge2XhHr0MjThj.jpg',  'First Day of School alumni cards 2026 at Marshmallow Nursery',  1440,  1920,  2],
    ];

    private const COVERS = [
        ['class', 'cupcake', 'uploads/classroom/1/FGeJL5SJi3YRqYuWls0xqfyb.jpg'],
        ['class', 'popcorn', 'uploads/classroom_activity/79/RLPTQll6X8znpTZcwqGZ5UOb.jpeg'],
        ['class', 'candy', 'uploads/classroom_activity/22/Mqw7fpc5eyMYZop1WTmxK8G0.jpg'],
        ['class', 'ice-cream', 'uploads/classroom_activity/33/9n9j1Tpvjn44IAE0GUEbPKws.jpg'],
        ['class', 'lollipop', 'uploads/classroom_activity/45/bJ12l8JKmedy1uUBsTQisAY6.jpg'],
        ['class', 'cotton-candy', 'uploads/classroom_activity/57/Z3TWilbWZ5nPSgaf3iJ2BmSy.jpg'],
        ['album', 'graduation-2026-under-the-sea', 'uploads/album/1/keh4bHVfKY9iF6Gblb04QVme.jpg'],
        ['album', 'solar-system-competition', 'uploads/album/2/CEVvvmNcFtzTgRZQGJXZ3y8Z.jpg'],
        ['album', 'pyjama-camping-party-bedtime-stories', 'uploads/album/3/orHFigT6oXDlWNK8IAfKGHqr.jpg'],
        ['album', '6th-of-october-celebrations', 'uploads/album/4/ufP0pEUvIyj48c4JI4f2a19L.jpg'],
        ['album', 'trip-to-dolphina', 'uploads/album/6/h6Gua4iFZxdGmmZmvmkTkvRP.jpg'],
        ['album', 'summer-camp-2026', 'uploads/album/7/u9IvacIwO82rvA1au5BVkio7.jpg'],
        ['album', 'animals-visit', 'uploads/album/9/Avo0EFJpq7bnog2MQECwTmPD.jpg'],
        ['album', 'circus-day', 'uploads/album/10/EJLYgYYMJG5o2QDE6hFioTFL.jpg'],
        ['album', 'marshmallow-schools-expo', 'uploads/album/11/oYrIbhhrlbHzvAm0k3Wm4UBs.jpg'],
        ['album', 'parents-reviews', 'uploads/album/12/DrnFA6YZ2JpPbkJq4guOHSqj.jpg'],
        ['album', 'winter-camp-2026', 'uploads/album/13/jAG3SsHgBFq3UDAIYT9nxc7E.jpg'],
        ['album', 'spring-camp-2026', 'uploads/album/14/ocu841pTivtCikswlqFmfXoi.jpg'],
        ['album', 'halloween-2025', 'uploads/album/15/geyry4QthHffSNf2E9UXkuRm.jpg'],
        ['album', 'occupation-day-2026', 'uploads/album/16/OLlHI4z0k6XkVEZEsBrl69rU.jpg'],
        ['album', 'space-event-2026-fikrymo', 'uploads/album/17/me4sYIPRJV5C0fAPFhjOn4jm.jpg'],
        ['album', 'fathers-day-2026', 'uploads/album/18/W1AVF41xyCR3nePASchr1ZUw.jpg'],
        ['album', 'eid-al-adha-2026', 'uploads/album/19/Ew13j9wJhCNFxtE4g2FP8XET.jpg'],
        ['album', 'eid-al-fitr-2026', 'uploads/album/20/hsDPCVPSqEZXM2PhftoHZEZV.jpg'],
        ['album', 'ramadan-2026-suhoor-with-moms', 'uploads/album/21/lssCX5dyNzR4b481VmCDsktN.jpg'],
        ['album', 'ramadan-2026', 'uploads/album/22/csgua5LW1ygeATxw1xSsp4hQ.jpg'],
        ['album', 'easter-sham-el-nessim-2026', 'uploads/album/23/0iKpQmqEcyYprbOxGUAu7bbJ.jpg'],
        ['album', 'wacky-tacky-day-2025', 'uploads/album/24/kGHoiWIfOkd11G6o9TzH7K9O.jpg'],
        ['album', 'back-to-the-80s-party-2026', 'uploads/album/25/yIWuRPvDkRMD6LzlO4DID471.jpg'],
        ['album', 'trip-april-2026', 'uploads/album/26/D3M22QQmieMAANkOskMb0zcd.jpg'],
        ['album', 'trip-january-2026', 'uploads/album/27/Vl2Xf0mNk7EqRAi60OlSRpIT.jpg'],
        ['album', 'first-day-of-school-alumni-cards-2026', 'uploads/album/28/DhowTd6yYCOYn8irqkFAvlCt.jpg'],
    ];

    public function run(): void
    {
        $classrooms = Classroom::pluck('id', 'slug');
        $albums = GalleryAlbum::pluck('id', 'slug');
        $pivots = ClassroomActivity::with(['classroom:id,slug', 'activity:id,slug'])->get()
            ->mapWithKeys(fn ($p) => [$p->classroom->slug.'/'.$p->activity->slug => $p]);
        $seen = [];

        foreach (self::PHOTOS as [$kind, $slug, $activity, $path, $alt, $width, $height, $sort]) {
            $owner = match ($kind) {
                'class' => isset($classrooms[$slug]) ? Classroom::find($classrooms[$slug]) : null,
                'album' => isset($albums[$slug]) ? GalleryAlbum::find($albums[$slug]) : null,
                'class_activity' => $pivots[$slug.'/'.$activity] ?? null,
                default => null,
            };

            if (! $owner) {
                continue;
            }

            $key = $owner->getMorphClass().':'.$owner->getKey();
            if (! isset($seen[$key])) {
                $seen[$key] = $owner->photos()->exists();
            }
            if ($seen[$key]) {
                continue;
            }

            $owner->photos()->create(compact('path', 'alt', 'width', 'height') + ['sort_order' => $sort]);
        }

        foreach (self::COVERS as [$kind, $slug, $path]) {
            $model = $kind === 'class'
                ? Classroom::where('slug', $slug)->first()
                : GalleryAlbum::where('slug', $slug)->first();

            if ($model && ! $model->cover_image) {
                $model->update(['cover_image' => $path]);
            }
        }

        GalleryAlbum::doesntHave('photos')->update(['is_visible' => false]);
        GalleryAlbum::has('photos')->update(['is_visible' => true]);
    }
}
